# Configuración de Jekyll para GitHub Pages
title: "Generador Análisis Empresarial"
description: "Generador de reportes de inteligencia de negocio e investigación corporativa en tiempo real"
author: "Proyecto 3 - Grupo 2. TanDEM"
baseurl: "/Proyecto_3_Scrapper"
url: "https://kephril.github.io"

# Configuración de Jekyll
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Configuración de compilación
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# Configuración de GitHub Pages
repository: "Kephril/Proyecto_3_Scrapper"
github_username: "Kephril"

# Configuración de SEO
lang: es
twitter:
  username: 
  card: summary_large_image

# Configuración de navegación
navigation:
  - name: "Inicio"
    url: "/"
  - name: "Análisis"
    url: "/#report-form"

# Configuración de metadatos
google_analytics: 
google_site_verification: 
